---
# =====================================================================
#        File:  delete_azure_environment.yml
#    Location:  https://github.com/sa-ch/ansible-azure-deployment.git
#   Launguage:  Ansible Playbook
#    Category:  ansible
#     Purpose:  Dploy a new VM Instances on Microsoft Azure
#      Author:  Sacha Dubois, Red Hat, Email: sadubois@redhat.com
#               Peter Mumenthaler Red Hat, Email: pmumenth@redhat.com
#
# Copyright (c) 2010 - 2012 Red Hat, Inc.
# This software is licensed to you under the GNU General Public License,
# version 2 (GPLv2). There is NO WARRANTY for this software, express or
# implied, including the implied warranties of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. You should have received a copy of GPLv2
# along with this software; if not, see
# http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt.
#
# Red Hat trademarks are not licensed under GPLv2. No permission is
# granted to use or replicate Red Hat trademarks that are incorporated
# in this software or its documentation.
# =====================================================================

- name: Create virtual machine
  hosts: localhost
  vars: 
    - debug: 0
  pre_tasks:
    - fail:
       msg: "usage: ansible-playbook -e location_name=<location> delete_azure_environment.yml"
      when: location_name is not defined
  tasks:
    - debug:
        var: location_name
      when: debug == 1

    - name: Include Azure Environment (azure_westeurope or azure_easteurope)
      include_vars: files/{{ location_name }}.yml

    - name: Delete storage account ({{ storage_account }})
      azure_rm_storageaccount:
        resource_group: "{{ resourcegrp }}"
        name: "{{ storage_account }}"
        account_type: "{{ storage_account_type }}"
        state: absent

#    - name: "Delete subnet: {{ subnet }}"
#      azure_rm_subnet:
#        resource_group: "{{ resourcegrp }}"
#        name: "{{ subnet }}"
#        address_prefix: "{{ sub_address_prefix }}"
#        virtual_network: "{{ virtualnetwork }}"
#        state: absent

    - name: "Delete virtual network: {{ virtualnetwork }}"
      azure_rm_virtualnetwork:
        resource_group: "{{ resourcegrp }}"
        name: "{{ virtualnetwork }}"
        address_prefixes: "10.10.0.0/16"
        state: absent

    - name: "Delete security group: {{ securitygrp }}"
      azure_rm_securitygroup:
        resource_group: "{{ resourcegrp }}"
        name: "{{ securitygrp }}"
        rules:
          - name: SSH
            protocol: Tcp
            destination_port_range: 22
            access: Allow
            priority: 101
            direction: Inbound
          - name: HTTP
            protocol: Tcp
            destination_port_range: 80
            access: Allow
            priority: 102
            direction: Inbound
        state: absent

    - name: "Delete resource group: {{ resourcegrp }} in location: {{ location }}"
      azure_rm_resourcegroup:
        name: "{{ resourcegrp }}"
        location: "{{ location }}" 
        state: absent

