---
# =====================================================================
#        File:  create_instance.yml
#    Location:  https://github.com/sa-ch/ansible-azure-deployment.git
#   Launguage:  Ansible Playbook
#    Category:  ansible
#     Purpose:  Dploy a new VM Instances on Microsoft Azure
#      Author:  Sacha Dubois, Red Hat, Email: sadubois@redhat.com
#               Peter Mumenthaler Red Hat, Email: pmumenth@redhat.com
#
# Copyright (c) 2010 - 2012 Red Hat, Inc.
# This software is licensed to you under the GNU General Public License,
# version 2 (GPLv2). There is NO WARRANTY for this software, express or
# implied, including the implied warranties of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. You should have received a copy of GPLv2
# along with this software; if not, see
# http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt.
#
# Red Hat trademarks are not licensed under GPLv2. No permission is
# granted to use or replicate Red Hat trademarks that are incorporated
# in this software or its documentation.
# =====================================================================


    - name: Include Azure Environment
      include_vars: files/{{ location_name }}.yml

    - name: "Create public ip: pip_{{ vmname }}"
      azure_rm_publicipaddress:
        resource_group: "{{ resourcegrp }}"
        allocation_method: "{{ allocation_method }}"
        name: "pip_{{ vmname }}"
        state: "{{ state_toggle }}"

    - name: "Create NIC: nic_{{ vmname }}"
      azure_rm_networkinterface:
        resource_group: "{{ resourcegrp }}"
        name: "nic_{{ vmname }}"
        virtual_network: "{{ virtualnetwork }}"
        subnet: "{{ subnet }}"
        public_ip_name: "pip_{{ vmname }}"
        security_group: "{{ securitygrp }}"
        state: "{{ state_toggle }}"

    - name: Create virtual machine {{ vmname }}
      azure_rm_virtualmachine:
        resource_group: "{{ resourcegrp }}"
        name: "{{ vmname }}"
        vm_size: "{{ vm_size }}"
        storage_account: "{{ storage_account }}"
        storage_container: "{{ vmname }}"
        storage_blob: "{{ vmname }}.vhd"
        admin_username: "{{ admin_username }}"
        admin_password: "{{ admin_password }}"
        network_interfaces: "nic_{{ vmname }}"
        ssh_public_keys: 
          - path: /home/ansible/.ssh/authorized_keys
            key_data: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC55gMWnehtZ2D6v8m8Qh6ZuVdUgeH9sdcIpTgdq6dwbsJ8wqyXrfQU8NLsHTVxHCbWC/ux2hyOK6MAPxOUSC4X6u+asx61RRn39mUaJ/0qfpwAtP7/059ZxEHs/rZz21jm9HR9sqUrowqgwgbTX8FkDCR6AhqHE+naiWfA0DeIJ5Iywd2hdb2LlncA0fGdlwFPqfKRdOfRIrt4KADt4rR3X5q1m1P+QcuptGxx6CA/a3WLIMfLd6Kb7AgA5mRrC0DSvwUwJhnLD/b2YYQmBoX3G5d2kG2GQoCLjGxdUlU4L+Zc12hS15yqIhAVbRLkkVCeVZrab7pisvA+NjVr5c6J ansible@ansible.rhlab.ch
        image:
          offer: CentOS
          publisher: OpenLogic
          sku: 7.4
          version: latest
      register: vmstat
    - debug: 
        var: vmstat.ansible_facts.azure_vm.properties.networkProfile.networkInterfaces[0].properties.ipConfigurations[0].properties.publicIPAddress.properties.ipAddress
      when: debug > 0

    - name: Add host to /etc/hosts
      lineinfile:
        path: /etc/hosts
        regexp: '^.* {{ vmname }}$'
        line: "{{ ipa }} {{ vmname }}"
      become: true
      vars: 
        ipa: "{{ vmstat.ansible_facts.azure_vm.properties.networkProfile.networkInterfaces[0].properties.ipConfigurations[0].properties.publicIPAddress.properties.ipAddress }}"
      delegate_to: ansible.rhlab.ch
      remote_user: ansible

    - name: Remove old known_host entry
      lineinfile:
        regexp: "^{{ vmname }}"
        state: absent
        path: /home/ansible/.ssh/known_hosts
      delegate_to: ansible.rhlab.ch
      remote_user: ansible
      
    - name: add ssh host key
      command: /bin/ssh-keyscan -t ecdsa-sha2-nistp256 srv001 >> /home/ansible/.ssh/known_hosts
      delegate_to: ansible.rhlab.ch
      remote_user: ansible
      
    - name: add ssh host key
      shell: /bin/ssh-keyscan -t ecdsa-sha2-nistp256 srv001 >> /home/ansible/.ssh/known_hosts
      args:
        executable: /bin/bash
      delegate_to: ansible.rhlab.ch
      remote_user: ansible





